#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENTRY_FILE="$ROOT_DIR/src/runtime-globals.entry.js"
OUT_FILE="$ROOT_DIR/src/runtime-globals.js"

npx --yes esbuild "$ENTRY_FILE" \
  --bundle \
  --format=iife \
  --platform=browser \
  --target=es2020 \
  --banner:js="// AUTO-GENERATED by scripts/build-runtime-globals.sh. Do not edit by hand." \
  --log-level=warning \
  --outfile="$OUT_FILE"

echo "Built $OUT_FILE"
