// AUTO-GENERATED by scripts/build-runtime-globals.sh. Do not edit by hand.
(() => {
  // src/state/app-state.js
  function createStore(initialState = {}) {
    let state = { ...initialState };
    const listeners = /* @__PURE__ */ new Set();
    function getState() {
      return state;
    }
    function setState(partialOrUpdater) {
      const partial = typeof partialOrUpdater === "function" ? partialOrUpdater(state) : partialOrUpdater;
      if (!partial || typeof partial !== "object") {
        return state;
      }
      const previousState = state;
      state = {
        ...state,
        ...partial
      };
      listeners.forEach((listener) => {
        listener(state, previousState);
      });
      return state;
    }
    function subscribe(listener) {
      if (typeof listener !== "function") {
        return () => {
        };
      }
      listeners.add(listener);
      return () => {
        listeners.delete(listener);
      };
    }
    return {
      getState,
      setState,
      subscribe
    };
  }

  // src/state/actions.js
  function toNonNegativeInteger(value) {
    const numeric = Number(value);
    if (!Number.isFinite(numeric) || numeric < 0) {
      return 0;
    }
    return Math.round(numeric);
  }
  function sanitizeTripCode(value) {
    return String(value || "").trim().toLowerCase().slice(0, 80);
  }
  function sanitizePackItems(rawItems) {
    if (!Array.isArray(rawItems)) {
      return [];
    }
    let fallbackId = 1;
    return rawItems.filter((item) => item && (typeof item.text === "string" || typeof item.label === "string")).map((item) => {
      const text = String(item.text ?? item.label).trim().slice(0, 100);
      const rawId = Number(item.id);
      const id = Number.isFinite(rawId) && rawId > 0 ? rawId : fallbackId++;
      return {
        id,
        text,
        done: Boolean(item.done ?? item.checked)
      };
    }).filter((item) => item.text.length > 0);
  }
  function sanitizeBudgetState(rawBudget) {
    const parsed = rawBudget && typeof rawBudget === "object" ? rawBudget : {};
    const maxBudgetISK = toNonNegativeInteger(parsed.maxBudgetISK);
    const expenses = Array.isArray(parsed.expenses) ? parsed.expenses.filter((item) => item && typeof item.name === "string").map((item, index) => ({
      id: Number.isFinite(Number(item.id)) ? Number(item.id) : index + 1,
      name: String(item.name).trim().slice(0, 100),
      amountISK: toNonNegativeInteger(item.amountISK),
      createdAt: Number.isFinite(Number(item.createdAt)) ? Number(item.createdAt) : null
    })).filter((item) => item.name.length > 0) : [];
    return {
      maxBudgetISK,
      expenses
    };
  }
  function sanitizeActiveTab(value) {
    const allowedTabs = /* @__PURE__ */ new Set(["home", "itinerary", "tools"]);
    return allowedTabs.has(value) ? value : "home";
  }
  function sanitizeDisabledLocations(rawState) {
    if (!rawState || typeof rawState !== "object") {
      return {};
    }
    const sanitized = {};
    Object.keys(rawState).forEach((rawKey) => {
      const key = String(rawKey || "").trim();
      if (!key || key.length > 120 || !/^[a-z0-9:_-]+$/i.test(key)) {
        return;
      }
      if (rawState[rawKey]) {
        sanitized[key] = true;
      }
    });
    return sanitized;
  }
  function createActions(store) {
    const { getState, setState } = store;
    return {
      hydrate(partialState) {
        return setState(partialState);
      },
      setPackItems(items) {
        return setState({
          packItems: sanitizePackItems(items)
        });
      },
      togglePackItem(id) {
        const numericId = Number(id);
        return setState((state) => ({
          packItems: (state.packItems || []).map(
            (item) => item.id === numericId ? { ...item, done: !Boolean(item.done) } : item
          )
        }));
      },
      addPackItem(payload) {
        const nextItem = payload && typeof payload === "object" ? payload : {};
        const id = Number(nextItem.id);
        const text = String(nextItem.text || "").trim().slice(0, 100);
        if (!Number.isFinite(id) || id <= 0 || !text) {
          return getState();
        }
        return setState((state) => ({
          packItems: [
            ...state.packItems || [],
            {
              id,
              text,
              done: Boolean(nextItem.done)
            }
          ]
        }));
      },
      updatePackItemText(id, text) {
        const numericId = Number(id);
        const nextText = String(text || "").trim().slice(0, 100);
        if (!nextText) {
          return getState();
        }
        return setState((state) => ({
          packItems: (state.packItems || []).map(
            (item) => item.id === numericId ? { ...item, text: nextText } : item
          )
        }));
      },
      removePackItem(id) {
        const numericId = Number(id);
        return setState((state) => ({
          packItems: (state.packItems || []).filter((item) => item.id !== numericId)
        }));
      },
      setBudget(nextBudget) {
        return setState({
          budget: sanitizeBudgetState(nextBudget)
        });
      },
      setBudgetMaxISK(maxBudgetISK) {
        return setState((state) => ({
          budget: {
            ...state.budget || { maxBudgetISK: 0, expenses: [] },
            maxBudgetISK: toNonNegativeInteger(maxBudgetISK)
          }
        }));
      },
      addExpense(expense) {
        const nextExpense = expense && typeof expense === "object" ? expense : {};
        const id = Number(nextExpense.id);
        const name = String(nextExpense.name || "").trim().slice(0, 100);
        const amountISK = toNonNegativeInteger(nextExpense.amountISK);
        const createdAt = Number.isFinite(Number(nextExpense.createdAt)) ? Number(nextExpense.createdAt) : Date.now();
        if (!Number.isFinite(id) || id <= 0 || !name || !amountISK) {
          return getState();
        }
        return setState((state) => ({
          budget: {
            ...state.budget || { maxBudgetISK: 0, expenses: [] },
            expenses: [
              ...state.budget && state.budget.expenses || [],
              {
                id,
                name,
                amountISK,
                createdAt
              }
            ]
          }
        }));
      },
      updateExpense(id, patch) {
        const numericId = Number(id);
        const patchObject = patch && typeof patch === "object" ? patch : {};
        return setState((state) => ({
          budget: {
            ...state.budget || { maxBudgetISK: 0, expenses: [] },
            expenses: (state.budget && state.budget.expenses || []).map((expense) => {
              if (expense.id !== numericId) {
                return expense;
              }
              const nextName = typeof patchObject.name === "string" ? patchObject.name.trim().slice(0, 100) : expense.name;
              const nextAmount = patchObject.amountISK === void 0 ? expense.amountISK : toNonNegativeInteger(patchObject.amountISK);
              return {
                ...expense,
                name: nextName || expense.name,
                amountISK: nextAmount
              };
            })
          }
        }));
      },
      removeExpense(id) {
        const numericId = Number(id);
        return setState((state) => ({
          budget: {
            ...state.budget || { maxBudgetISK: 0, expenses: [] },
            expenses: (state.budget && state.budget.expenses || []).filter(
              (expense) => expense.id !== numericId
            )
          }
        }));
      },
      setActiveTab(tab) {
        return setState({
          activeTab: sanitizeActiveTab(tab)
        });
      },
      setModuleCollapseState(moduleCollapse) {
        const nextState = moduleCollapse && typeof moduleCollapse === "object" ? moduleCollapse : {};
        return setState({
          moduleCollapse: { ...nextState }
        });
      },
      setModuleCollapsed(moduleKey, collapsed) {
        return setState((state) => ({
          moduleCollapse: {
            ...state.moduleCollapse || {},
            [moduleKey]: Boolean(collapsed)
          }
        }));
      },
      setDisabledLocations(nextState) {
        return setState({
          disabledLocations: sanitizeDisabledLocations(nextState)
        });
      },
      setLocationDisabled(locationKey, disabled) {
        const key = String(locationKey || "").trim();
        if (!key || key.length > 120 || !/^[a-z0-9:_-]+$/i.test(key)) {
          return getState();
        }
        return setState((state) => {
          const current = sanitizeDisabledLocations(state.disabledLocations);
          if (disabled) {
            current[key] = true;
          } else {
            delete current[key];
          }
          return {
            disabledLocations: current
          };
        });
      },
      setSyncSettings(nextSettingsOrUpdater) {
        return setState((state) => {
          const current = state.syncSettings || {
            tripId: "",
            autoSync: true
          };
          const next = typeof nextSettingsOrUpdater === "function" ? nextSettingsOrUpdater(current) : nextSettingsOrUpdater;
          const parsed = next && typeof next === "object" ? next : {};
          return {
            syncSettings: {
              tripId: sanitizeTripCode(parsed.tripId),
              autoSync: parsed.autoSync !== false
            }
          };
        });
      },
      setTodayOverview(nextOverviewOrUpdater) {
        return setState((state) => {
          const current = state.todayOverview || {};
          const next = typeof nextOverviewOrUpdater === "function" ? nextOverviewOrUpdater(current) : nextOverviewOrUpdater;
          if (!next || typeof next !== "object") {
            return {};
          }
          return {
            todayOverview: {
              ...current,
              ...next
            }
          };
        });
      }
    };
  }
  var stateSanitizers = {
    sanitizePackItems,
    sanitizeBudgetState,
    sanitizeDisabledLocations
  };

  // src/storage/local-storage-adapter.js
  function createLocalStorageAdapter(storageRef) {
    const storage = storageRef || (typeof window !== "undefined" && window.localStorage ? window.localStorage : null);
    function load(key) {
      if (!storage) {
        return null;
      }
      try {
        const raw = storage.getItem(String(key));
        if (!raw) {
          return null;
        }
        return JSON.parse(raw);
      } catch {
        return null;
      }
    }
    function save(key, value) {
      if (!storage) {
        return false;
      }
      try {
        storage.setItem(String(key), JSON.stringify(value));
        return true;
      } catch {
        return false;
      }
    }
    function remove(key) {
      if (!storage) {
        return false;
      }
      try {
        storage.removeItem(String(key));
        return true;
      } catch {
        return false;
      }
    }
    function watch(key, handler) {
      if (typeof window === "undefined" || typeof window.addEventListener !== "function" || typeof handler !== "function") {
        return () => {
        };
      }
      const storageKey = String(key);
      const listener = (event) => {
        if (event.storageArea !== storage || event.key !== storageKey) {
          return;
        }
        let nextValue = null;
        try {
          nextValue = event.newValue ? JSON.parse(event.newValue) : null;
        } catch {
          nextValue = null;
        }
        handler(nextValue);
      };
      window.addEventListener("storage", listener);
      return () => {
        window.removeEventListener("storage", listener);
      };
    }
    return {
      load,
      save,
      remove,
      watch
    };
  }

  // src/storage/indexeddb-adapter.js
  function createNoopAdapter() {
    return {
      async load() {
        return null;
      },
      async save() {
        return false;
      },
      async remove() {
        return false;
      },
      watch() {
        return () => {
        };
      }
    };
  }
  function createIndexedDbAdapter(options = {}) {
    if (typeof indexedDB === "undefined") {
      return createNoopAdapter();
    }
    const dbName = String(options.dbName || "iceland-trip");
    const storeName = String(options.storeName || "kv");
    const version = Number.isFinite(Number(options.version)) ? Number(options.version) : 1;
    let openPromise = null;
    function openDatabase() {
      if (openPromise) {
        return openPromise;
      }
      openPromise = new Promise((resolve, reject) => {
        const request = indexedDB.open(dbName, version);
        request.onupgradeneeded = () => {
          const db = request.result;
          if (!db.objectStoreNames.contains(storeName)) {
            db.createObjectStore(storeName);
          }
        };
        request.onsuccess = () => {
          resolve(request.result);
        };
        request.onerror = () => {
          reject(request.error || new Error("IndexedDB open failed"));
        };
      });
      return openPromise;
    }
    async function withStore(mode, callback) {
      try {
        const db = await openDatabase();
        return await new Promise((resolve, reject) => {
          const transaction = db.transaction(storeName, mode);
          const objectStore = transaction.objectStore(storeName);
          const result = callback(objectStore);
          transaction.oncomplete = () => resolve(result);
          transaction.onerror = () => reject(transaction.error || new Error("IndexedDB transaction failed"));
        });
      } catch {
        return null;
      }
    }
    async function load(key) {
      return withStore("readonly", (store) => {
        return new Promise((resolve, reject) => {
          const request = store.get(String(key));
          request.onsuccess = () => resolve(request.result ?? null);
          request.onerror = () => reject(request.error);
        });
      });
    }
    async function save(key, value) {
      const result = await withStore("readwrite", (store) => {
        store.put(value, String(key));
        return true;
      });
      return Boolean(result);
    }
    async function remove(key) {
      const result = await withStore("readwrite", (store) => {
        store.delete(String(key));
        return true;
      });
      return Boolean(result);
    }
    return {
      load,
      save,
      remove,
      watch() {
        return () => {
        };
      }
    };
  }

  // src/storage/supabase-adapter.js
  function createNoopAdapter2() {
    return {
      async load() {
        return null;
      },
      async save() {
        return false;
      },
      async remove() {
        return false;
      },
      watch() {
        return () => {
        };
      }
    };
  }
  function createSupabaseAdapter(options = {}) {
    const client = options.client || null;
    const table = String(options.table || "");
    const keyColumn = String(options.keyColumn || "key");
    const valueColumn = String(options.valueColumn || "value");
    if (!client || !table) {
      return createNoopAdapter2();
    }
    async function load(key) {
      try {
        const response = await client.from(table).select(valueColumn).eq(keyColumn, String(key)).limit(1).maybeSingle();
        if (response.error) {
          return null;
        }
        return response.data ? response.data[valueColumn] : null;
      } catch {
        return null;
      }
    }
    async function save(key, value) {
      try {
        const response = await client.from(table).upsert(
          [{ [keyColumn]: String(key), [valueColumn]: value }],
          { onConflict: keyColumn }
        );
        return !response.error;
      } catch {
        return false;
      }
    }
    async function remove(key) {
      try {
        const response = await client.from(table).delete().eq(keyColumn, String(key));
        return !response.error;
      } catch {
        return false;
      }
    }
    function watch(key, handler) {
      if (typeof handler !== "function" || typeof client.channel !== "function") {
        return () => {
        };
      }
      const watchedKey = String(key);
      const channelName = "storage_watch_" + table + "_" + watchedKey + "_" + Math.random().toString(36).slice(2, 8);
      const channel = client.channel(channelName).on(
        "postgres_changes",
        {
          event: "*",
          schema: "public",
          table,
          filter: keyColumn + "=eq." + watchedKey
        },
        (payload) => {
          const row = payload && payload.new ? payload.new : null;
          handler(row ? row[valueColumn] : null);
        }
      ).subscribe();
      return () => {
        try {
          client.removeChannel(channel);
        } catch {
        }
      };
    }
    return {
      load,
      save,
      remove,
      watch
    };
  }

  // src/main.js
  var DEFAULT_SCHEMA_VERSION = 1;
  var DEFAULT_APP_STATE_KEY = "icelandAppStateV1";
  var DEFAULT_RECEIPTS_META_KEY = "icelandReceiptsMetaV1";
  var DEFAULT_RECEIPTS_BLOB_STORE = "receipts";
  function toSchemaVersion(value) {
    const numeric = Number(value);
    return Number.isFinite(numeric) && numeric > 0 ? Math.round(numeric) : DEFAULT_SCHEMA_VERSION;
  }
  function createDefaultState(schemaVersion) {
    return {
      schemaVersion,
      packItems: [],
      disabledLocations: {},
      budget: {
        maxBudgetISK: 0,
        expenses: []
      },
      activeTab: "home",
      moduleCollapse: {},
      syncSettings: {
        tripId: "",
        autoSync: true
      },
      todayOverview: {
        lastUpdatedAt: null
      }
    };
  }
  function migrateState(rawState, targetSchemaVersion = DEFAULT_SCHEMA_VERSION) {
    const schemaVersion = toSchemaVersion(targetSchemaVersion);
    const base = createDefaultState(schemaVersion);
    const raw = rawState && typeof rawState === "object" ? rawState : {};
    return {
      ...base,
      ...raw,
      schemaVersion,
      packItems: stateSanitizers.sanitizePackItems(raw.packItems),
      disabledLocations: stateSanitizers.sanitizeDisabledLocations(raw.disabledLocations),
      budget: stateSanitizers.sanitizeBudgetState(raw.budget),
      moduleCollapse: raw.moduleCollapse && typeof raw.moduleCollapse === "object" ? raw.moduleCollapse : {},
      syncSettings: {
        tripId: String(
          raw.syncSettings && typeof raw.syncSettings.tripId === "string" ? raw.syncSettings.tripId : ""
        ).trim().toLowerCase().slice(0, 80),
        autoSync: !raw.syncSettings || raw.syncSettings.autoSync !== false
      },
      todayOverview: raw.todayOverview && typeof raw.todayOverview === "object" ? raw.todayOverview : { lastUpdatedAt: null }
    };
  }
  function mergeInitialState(schemaVersion, persistedState, providedState) {
    const defaults = createDefaultState(schemaVersion);
    const persisted = migrateState(persistedState, schemaVersion);
    const provided = migrateState(providedState, schemaVersion);
    return {
      ...defaults,
      ...persisted,
      ...provided,
      budget: {
        ...defaults.budget,
        ...persisted.budget,
        ...provided.budget
      },
      disabledLocations: {
        ...defaults.disabledLocations,
        ...persisted.disabledLocations,
        ...provided.disabledLocations
      },
      syncSettings: {
        ...defaults.syncSettings,
        ...persisted.syncSettings,
        ...provided.syncSettings
      },
      moduleCollapse: {
        ...defaults.moduleCollapse,
        ...persisted.moduleCollapse,
        ...provided.moduleCollapse
      },
      todayOverview: {
        ...defaults.todayOverview,
        ...persisted.todayOverview,
        ...provided.todayOverview
      }
    };
  }
  function createPersistence(adapterSet, options = {}) {
    const localStorage = adapterSet.localStorage;
    const indexeddb = adapterSet.indexeddb;
    const supabase = adapterSet.supabase;
    const appStateStorageKey = String(options.appStateStorageKey || DEFAULT_APP_STATE_KEY);
    const receiptsMetaStorageKey = String(
      options.receiptsMetaStorageKey || DEFAULT_RECEIPTS_META_KEY
    );
    return {
      loadDomain(key, fallbackValue) {
        const value = localStorage.load(key);
        return value === null || value === void 0 ? fallbackValue : value;
      },
      saveDomain(key, value) {
        return localStorage.save(key, value);
      },
      removeDomain(key) {
        return localStorage.remove(key);
      },
      loadAppSnapshot() {
        return localStorage.load(appStateStorageKey);
      },
      saveAppSnapshot(snapshot) {
        return localStorage.save(appStateStorageKey, snapshot);
      },
      loadReceiptsMeta() {
        const meta = localStorage.load(receiptsMetaStorageKey);
        return meta && typeof meta === "object" ? meta : {};
      },
      saveReceiptsMeta(meta) {
        return localStorage.save(receiptsMetaStorageKey, meta || {});
      },
      async saveReceiptBlob(receiptId, blobOrValue) {
        return indexeddb.save("receipt:" + String(receiptId), blobOrValue);
      },
      async loadReceiptBlob(receiptId) {
        return indexeddb.load("receipt:" + String(receiptId));
      },
      async removeReceiptBlob(receiptId) {
        return indexeddb.remove("receipt:" + String(receiptId));
      },
      async saveSharedState(key, value) {
        return supabase.save(key, value);
      },
      async loadSharedState(key) {
        return supabase.load(key);
      },
      watchSharedState(key, handler) {
        return supabase.watch(key, handler);
      }
    };
  }
  function createAppRuntime(options = {}) {
    const schemaVersion = toSchemaVersion(options.schemaVersion);
    const adapters = {
      localStorage: createLocalStorageAdapter(options.localStorage),
      indexeddb: createIndexedDbAdapter({
        dbName: options.indexeddbName || "iceland-trip",
        storeName: options.indexeddbStoreName || DEFAULT_RECEIPTS_BLOB_STORE,
        version: options.indexeddbVersion || 1
      }),
      supabase: createSupabaseAdapter({
        client: options.supabaseClient,
        table: options.supabaseTable || "",
        keyColumn: options.supabaseKeyColumn || "key",
        valueColumn: options.supabaseValueColumn || "value"
      })
    };
    const persistence = createPersistence(adapters, {
      appStateStorageKey: options.appStateStorageKey,
      receiptsMetaStorageKey: options.receiptsMetaStorageKey
    });
    const persistedState = persistence.loadAppSnapshot();
    const initialState = mergeInitialState(
      schemaVersion,
      persistedState,
      options.initialState
    );
    const store = createStore(initialState);
    const actions = createActions(store);
    function migrateSyncedPayload(payload) {
      const parsed = payload && typeof payload === "object" ? payload : {};
      const payloadVersion = toSchemaVersion(parsed.schemaVersion);
      if (payloadVersion <= 1) {
        return {
          schemaVersion,
          packItems: stateSanitizers.sanitizePackItems(parsed.packItems),
          disabledLocations: stateSanitizers.sanitizeDisabledLocations(parsed.disabledLocations),
          budgetState: stateSanitizers.sanitizeBudgetState(parsed.budgetState),
          syncSettings: parsed.syncSettings && typeof parsed.syncSettings === "object" ? parsed.syncSettings : null
        };
      }
      return {
        schemaVersion,
        packItems: stateSanitizers.sanitizePackItems(parsed.packItems),
        disabledLocations: stateSanitizers.sanitizeDisabledLocations(parsed.disabledLocations),
        budgetState: stateSanitizers.sanitizeBudgetState(parsed.budgetState),
        syncSettings: parsed.syncSettings && typeof parsed.syncSettings === "object" ? parsed.syncSettings : null
      };
    }
    return {
      schemaVersion,
      store,
      actions,
      adapters,
      persistence,
      migrateState,
      migrateSyncedPayload
    };
  }

  // src/features/packing/index.js
  var DEFAULT_PACK_ITEMS = [
    "Thermals (merino wool base layers)",
    "Warm mid-layer (fleece/wool sweater)",
    "Waterproof jacket (windproof)",
    "Waterproof pants (essential for waterfalls)",
    "Waterproof hiking boots",
    "Microspikes/Crampons",
    "Warm beanie hat & scarf/buff",
    "Waterproof gloves",
    "Swimsuit & quick-dry towel",
    "Power bank for phones",
    "Lip balm & moisturizer",
    "Headlamp (for campsites)"
  ];
  function sanitizePackItems2(rawItems, fallbackItems = DEFAULT_PACK_ITEMS) {
    if (!Array.isArray(rawItems)) {
      return fallbackItems.map((text, index) => ({
        id: index + 1,
        text,
        done: false
      }));
    }
    let fallbackId = 1;
    const items = rawItems.filter((item) => item && (typeof item.text === "string" || typeof item.label === "string")).map((item) => {
      const text = String(item.text ?? item.label).trim().slice(0, 100);
      const rawId = Number(item.id);
      const id = Number.isFinite(rawId) && rawId > 0 ? rawId : fallbackId++;
      return {
        id,
        text,
        done: Boolean(item.done ?? item.checked)
      };
    }).filter((item) => item.text.length > 0);
    if (items.length) {
      return items;
    }
    return fallbackItems.map((text, index) => ({
      id: index + 1,
      text,
      done: false
    }));
  }
  function computeNextPackId(items) {
    return Array.isArray(items) && items.length ? Math.max(...items.map((item) => Number(item.id) || 0)) + 1 : 1;
  }
  function createPackingFeature(options) {
    const {
      listEl,
      progressEl,
      progressLabelEl,
      progressPctEl,
      addItemFormEl,
      newItemInputEl,
      getItems,
      actions,
      onPersist
    } = options;
    const getCurrentItems = typeof getItems === "function" ? getItems : () => [];
    const persist = typeof onPersist === "function" ? onPersist : () => {
    };
    let nextPackId = computeNextPackId(getCurrentItems());
    function refreshNextPackId() {
      nextPackId = computeNextPackId(getCurrentItems());
    }
    function updatePackProgress() {
      if (!progressEl || !progressLabelEl || !progressPctEl) {
        return;
      }
      const items = getCurrentItems();
      const total = items.length;
      const checked = items.filter((item) => item.done).length;
      const ratio = total === 0 ? 0 : checked / total * 100;
      progressEl.style.width = ratio + "%";
      progressLabelEl.textContent = checked + " / " + total + " packed";
      progressPctEl.textContent = Math.round(ratio) + "%";
    }
    function renderPackList() {
      if (!listEl) {
        return;
      }
      listEl.innerHTML = "";
      const items = getCurrentItems();
      items.forEach((item) => {
        const row = document.createElement("div");
        row.className = "pack-item";
        row.dataset.id = String(item.id);
        const checkbox = document.createElement("input");
        checkbox.type = "checkbox";
        checkbox.checked = Boolean(item.done);
        checkbox.setAttribute("aria-label", "Mark item packed");
        const label = document.createElement("span");
        label.className = "pack-label" + (item.done ? " done" : "");
        label.textContent = item.text;
        const actionsEl = document.createElement("div");
        actionsEl.className = "item-actions";
        const editBtn = document.createElement("button");
        editBtn.className = "act-btn";
        editBtn.type = "button";
        editBtn.title = "Edit item";
        editBtn.setAttribute("aria-label", "Edit item");
        editBtn.innerHTML = '<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.3" stroke-linecap="round" stroke-linejoin="round"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg>';
        const removeBtn = document.createElement("button");
        removeBtn.className = "act-btn del";
        removeBtn.type = "button";
        removeBtn.title = "Remove item";
        removeBtn.setAttribute("aria-label", "Remove item");
        removeBtn.innerHTML = '<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.3" stroke-linecap="round" stroke-linejoin="round"><polyline points="3 6 5 6 21 6"/><path d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6"/><path d="M10 11v6M14 11v6"/><path d="M9 6V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2"/></svg>';
        checkbox.addEventListener("change", () => {
          actions.togglePackItem(item.id);
          persist();
          renderPackList();
        });
        editBtn.addEventListener("click", () => {
          startPackItemEdit(item.id);
        });
        removeBtn.addEventListener("click", () => {
          actions.removePackItem(item.id);
          refreshNextPackId();
          persist();
          renderPackList();
        });
        label.addEventListener("dblclick", () => {
          startPackItemEdit(item.id);
        });
        actionsEl.appendChild(editBtn);
        actionsEl.appendChild(removeBtn);
        row.appendChild(checkbox);
        row.appendChild(label);
        row.appendChild(actionsEl);
        listEl.appendChild(row);
      });
      updatePackProgress();
    }
    function startPackItemEdit(id) {
      if (!listEl) {
        return;
      }
      const item = getCurrentItems().find((entry) => entry.id === id);
      const row = listEl.querySelector('[data-id="' + id + '"]');
      if (!item || !row) {
        return;
      }
      const label = row.querySelector(".pack-label");
      const actionsEl = row.querySelector(".item-actions");
      if (!label || !actionsEl) {
        return;
      }
      const input = document.createElement("input");
      input.type = "text";
      input.className = "pack-edit-input";
      input.value = item.text;
      input.maxLength = 100;
      label.replaceWith(input);
      actionsEl.style.visibility = "hidden";
      input.focus();
      input.select();
      const commit = () => {
        const value = input.value.trim();
        if (value) {
          actions.updatePackItemText(id, value);
          persist();
        }
        renderPackList();
      };
      input.addEventListener("blur", commit);
      input.addEventListener("keydown", (event) => {
        if (event.key === "Enter") {
          event.preventDefault();
          input.blur();
        }
        if (event.key === "Escape") {
          renderPackList();
        }
      });
    }
    if (addItemFormEl) {
      addItemFormEl.addEventListener("submit", (event) => {
        event.preventDefault();
        const value = newItemInputEl ? newItemInputEl.value.trim().slice(0, 100) : "";
        if (!value) {
          return;
        }
        actions.addPackItem({
          id: nextPackId++,
          text: value,
          done: false
        });
        persist();
        renderPackList();
        if (newItemInputEl) {
          newItemInputEl.value = "";
          newItemInputEl.focus();
        }
      });
    }
    function setItems(items, options2 = {}) {
      actions.setPackItems(items);
      refreshNextPackId();
      persist(options2);
      renderPackList();
    }
    return {
      render: renderPackList,
      setItems,
      getItems: getCurrentItems,
      refreshNextPackId,
      startEdit: startPackItemEdit
    };
  }

  // src/runtime-globals.entry.js
  window.IcelandTripRuntimeLib = {
    createAppRuntime,
    createPackingFeature,
    DEFAULT_PACK_ITEMS,
    sanitizePackItems: sanitizePackItems2
  };
})();
