-- Aurora wake-up push alert subscriptions per device installation.
create table if not exists public.aurora_alert_subscriptions (
  id uuid primary key default gen_random_uuid(),
  installation_id text not null unique,
  enabled boolean not null default false,
  latitude double precision,
  longitude double precision,
  timezone text,
  onesignal_subscription_id text,
  permission text,
  language text,
  user_agent text,
  last_opened_at timestamptz,
  last_assessed_at timestamptz,
  last_assessment_level text,
  last_assessment_payload jsonb,
  last_notified_at timestamptz,
  last_notified_level text,
  last_notification_payload jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint aurora_alert_subscriptions_installation_chk
    check (installation_id ~ '^[a-z0-9][a-z0-9-]{5,120}$'),
  constraint aurora_alert_subscriptions_latitude_chk
    check (latitude is null or (latitude >= -90 and latitude <= 90)),
  constraint aurora_alert_subscriptions_longitude_chk
    check (longitude is null or (longitude >= -180 and longitude <= 180)),
  constraint aurora_alert_subscriptions_level_chk
    check (
      last_assessment_level is null
      or last_assessment_level in ('strong', 'weak', 'no', 'unknown')
    ),
  constraint aurora_alert_subscriptions_notified_level_chk
    check (
      last_notified_level is null
      or last_notified_level in ('strong', 'weak', 'no', 'unknown')
    )
);

comment on table public.aurora_alert_subscriptions is 'Per-device aurora push alert registration and notification history.';
comment on column public.aurora_alert_subscriptions.installation_id is 'Stable installation identifier generated by the PWA.';
comment on column public.aurora_alert_subscriptions.onesignal_subscription_id is 'OneSignal web push subscription/player identifier.';

create index if not exists aurora_alert_subscriptions_enabled_idx
  on public.aurora_alert_subscriptions (enabled)
  where enabled = true;

create index if not exists aurora_alert_subscriptions_last_notified_idx
  on public.aurora_alert_subscriptions (last_notified_at desc nulls last);

-- Reuse generic updated_at trigger from initial migration.
drop trigger if exists trg_aurora_alert_subscriptions_updated_at on public.aurora_alert_subscriptions;
create trigger trg_aurora_alert_subscriptions_updated_at
before update on public.aurora_alert_subscriptions
for each row
execute function public.set_trip_state_updated_at();

alter table public.aurora_alert_subscriptions enable row level security;

-- Restrict direct table access from anon/authenticated clients.
revoke all on table public.aurora_alert_subscriptions from anon, authenticated;

-- Service role is used by edge functions and bypasses RLS.
grant select, insert, update on table public.aurora_alert_subscriptions to service_role;

-- Cron schedule for edge function evaluation every 10 minutes.
do $cron$
declare
  existing_job_id bigint;
begin
  begin
    create extension if not exists pg_net with schema extensions;
  exception
    when others then
      raise notice 'Skipping pg_net setup: %', sqlerrm;
  end;

  begin
    create extension if not exists pg_cron with schema extensions;
  exception
    when others then
      raise notice 'Skipping pg_cron setup: %', sqlerrm;
  end;

  if exists (select 1 from pg_extension where extname = 'pg_cron')
    and exists (select 1 from pg_extension where extname = 'pg_net') then
    select jobid
      into existing_job_id
      from cron.job
      where jobname = 'aurora_alert_cron_every_10m'
      limit 1;

    if existing_job_id is not null then
      perform cron.unschedule(existing_job_id);
    end if;

    perform cron.schedule(
      'aurora_alert_cron_every_10m',
      '*/10 * * * *',
      $job$
      select
        net.http_post(
          url := 'https://btqfcutfmnrwvpvbwulw.supabase.co/functions/v1/aurora-alert-cron',
          headers := '{"Content-Type":"application/json","apikey":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0cWZjdXRmbW5yd3ZwdmJ3dWx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIzNjYyNDQsImV4cCI6MjA4Nzk0MjI0NH0.-DGZKD7BVWfaQkvr5LiKu9aNyBlO-pMJVgGnLWX9F6c","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0cWZjdXRmbW5yd3ZwdmJ3dWx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIzNjYyNDQsImV4cCI6MjA4Nzk0MjI0NH0.-DGZKD7BVWfaQkvr5LiKu9aNyBlO-pMJVgGnLWX9F6c"}'::jsonb,
          body := '{"source":"pg_cron"}'::jsonb
        ) as request_id;
      $job$
    );
  end if;
end;
$cron$;
